server:
  address: localhost
  port: 80
  servlet:
    context-path: /system

spring:
  application:
    name: employee-management-system
  #
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mng_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 2
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.mapper

system:
  admin:
    login-alive-time: 3600*24